branches:
 only:
 - master

sudo: true

language: c++
os:
- osx

env:
  global:
  - secure: "gc6JxERCuHuv1/JHxXg/VWva0GT5HxqjAiNozVmbh5r9TYeDEewAgEIKeGnCxoPsjr4lgdiJn9lK04L/clSItSPvLDhwpV5STkzQqcO3ZlXwWR5htvGS9xfujmD1zbK3ithzyLcI6+04lb+6Mb7p1QFXMTWQgOYhEUKMvQahxOQ="

compiler:
- clang

cache:
  directories:
  - $HOME/downloads

before_install:
# work-around for issue https://github.com/travis-ci/travis-ci/issues/6307
- curl -sSL https://rvm.io/mpapis.asc | gpg --import -
- curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
- rvm get stable

before_script:
# Downloads and extract Qt static build
- |
  set -e
  pushd $HOME/downloads
  curl -L -O https://github.com/jcfr/qt-static-build/releases/download/4.7.4-macosx-10.6-g%2B%2B/qt-everywhere-opensource-static-build-4.7.4.tar.gz
  tar -xzvf qt-everywhere-opensource-static-build-4.7.4.tar.gz
  sudo mkdir -p /Users/kitware/Dashboards/Support/
  sudo mv qt-everywhere-opensource-static-build-4.7.4 /Users/kitware/Dashboards/Support/
  popd
# Use scikit-ci-addons to
# * streamline installation of CMake
# * install package required to automatically create or update GitHub releases
- |
  mkdir $HOME/bin
  ln -s $(which pip2) $HOME/bin/pip
  pip install -U scikit-ci-addons
  ci_addons travis/install_cmake 3.8.0
script:
- |
  mkdir build
  cd build
  cmake \
    -DQT_QMAKE_EXECUTABLE:FILEPATH=/Users/kitware/Dashboards/Support/qt-everywhere-opensource-static-build-4.7.4/bin/qmake \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.6 \
    -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64 \
    ../
- make -j4 && make package
# Exclude tests requiring X Display
- ctest -LE XDisplayRequired -VV

deploy:
  - provider: script
    script: cd /Users/travis/build/commontk/AppLauncher && ci_addons publish_github_release commontk/applauncher --prerelease-packages build/CTKAppLauncher-*.tar.gz --prerelease-packages-clear-pattern "*macosx*" --prerelease-packages-keep-pattern "*<COMMIT_SHORT_SHA>*" --release-packages build/CTKAppLauncher-*.tar.gz
    skip_cleanup: true
    on:
      repo: commontk/AppLauncher
      branch: master
